# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d5677f05bbeb3efdd67ff6febce28b57703167d455cb4146b53145adbe213cf0b92c7e5c6de30ed4839efb92e5b36c5514ce80fa38117d23d4f461982853895

test:
  secret_key_base: f29dcaa31f4c612a8f4fd3a8c3a90eef22f306e2732f6425b814a6ce1b5380c3080c03af209ecf3155e1b70eceaffe7e05757db2a5d87c6c6dcd75080312bd44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
